### ISSUE TITLE
After upgrading to V6 package, compilation failes

### ISSUE THREAD

**Issue by gethari** [madoar/angular-archwizard#279]
Errors from the console
```
[34     get wizardSteps(): Array<WizardStep>;
           ~~~~~~~~~~~
node_modules/angular-archwizard/lib/components/wizard-navigation-bar.component.d.ts:40:9 - error TS1086: An accessor cannot be declared in an ambient context.

40     get numberOfWizardSteps(): number;
           ~~~~~~~~~~~~~~~~~~~
node_modules/angular-archwizard/lib/components/wizard.component.d.ts:64:9 - error TS1086: An accessor cannot be declared in an ambient context.

64     get defaultStepIndex(): number;
           ~~~~~~~~~~~~~~~~
node_modules/angular-archwizard/lib/components/wizard.component.d.ts:65:9 - error TS1086: An accessor cannot be declared in an ambient context.

65     set defaultStepIndex(defaultStepIndex: number);
           ~~~~~~~~~~~~~~~~
node_modules/angular-archwizard/lib/components/wizard.component.d.ts:101:9 - error TS1086: An accessor cannot be declared in an ambient context.

101     get horizontalOrientation(): boolean;
            ~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-archwizard/lib/components/wizard.component.d.ts:108:9 - error TS1086: An accessor cannot be declared in an ambient context.

108     get verticalOrientation(): boolean;
            ~~~~~~~~~~~~~~~~~~~
node_modules/angular-archwizard/lib/components/wizard.component.d.ts:121:9 - error TS1086: An accessor cannot be declared in an ambient context.

121     get currentStep(): WizardStep;
            ~~~~~~~~~~~
node_modules/angular-archwizard/lib/components/wizard.component.d.ts:126:9 - error TS1086: An accessor cannot be declared in an ambient context.

126     get completed(): boolean;
            ~~~~~~~~~
node_modules/angular-archwizard/lib/components/wizard.component.d.ts:130:9 - error TS1086: An accessor cannot be declared in an ambient context.

130     get wizardSteps(): WizardStep[];
            ~~~~~~~~~~~
node_modules/angular-archwizard/lib/components/wizard.component.d.ts:140:9 - error TS1086: An accessor cannot be declared in an ambient context.

140     get navigation(): NavigationMode;
            ~~~~~~~~~~
node_modules/angular-archwizard/lib/components/wizard.component.d.ts:146:9 - error TS1086: An accessor cannot be declared in an ambient context.

146     set navigation(navigation: NavigationMode);
            ~~~~~~~~~~
node_modules/angular-archwizard/lib/directives/go-to-step.directive.d.ts:67:9 - error TS1086: An accessor cannot be declared in an ambient context.

67     get finalize(): EventEmitter<void>;
           ~~~~~~~~
node_modules/angular-archwizard/lib/directives/go-to-step.directive.d.ts:73:9 - error TS1086: An accessor cannot be declared in an ambient context.

73     set finalize(emitter: EventEmitter<void>);
           ~~~~~~~~
node_modules/angular-archwizard/lib/directives/go-to-step.directive.d.ts:80:9 - error TS1086: An accessor cannot be declared in an ambient context.

80     get destinationStep(): number;
           ~~~~~~~~~~~~~~~
node_modules/angular-archwizard/lib/directives/next-step.directive.d.ts:33:9 - error TS1086: An accessor cannot be declared in an ambient context.

33     get finalize(): EventEmitter<void>;
           ~~~~~~~~
node_modules/angular-archwizard/lib/directives/next-step.directive.d.ts:39:9 - error TS1086: An accessor cannot be declared in an ambient context.

39     set finalize(emitter: EventEmitter<void>);
           ~~~~~~~~
node_modules/angular-archwizard/lib/directives/previous-step.directive.d.ts:34:9 - error TS1086: An accessor cannot be declared in an ambient context.

34     get finalize(): EventEmitter<void>;
           ~~~~~~~~
node_modules/angular-archwizard/lib/directives/previous-step.directive.d.ts:40:9 - error TS1086: An accessor cannot be declared in an ambient context.

40     set finalize(emitter: EventEmitter<void>);
           ~~~~~~~~
node_modules/angular-archwizard/lib/util/wizard-step.interface.d.ts:87:9 - error TS1086: An accessor cannot be declared in an ambient context.

87     get hidden(): boolean;
           ~~~~~~](url)
```

**Comment by madoar** [comment]
I believe you are using Angular 8 in your application, right? The error you are seeing most likely is because of a [breaking change](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#class-field-mitigations) in the typescript version that comes with Angular 9 which has been used to build version `6.0.0` of `angular-archwizard`. Therefore to use version `6.0.0` you will need to use Angular 9 in your application as well.

**Comment by gethari** [comment]
@madoar Thanks for the reply. I guessed it right. And Yes I'm using `Angular 8`
